[package]
name = "xolotl"
version = "0.0.1"
authors = ["Jeff Burdges <burdges@gnunet.org>"]

[dependencies]
arrayref = "^0.3"
rustc-serialize = "0.3"

rand = "^0.3"
siphasher = "^0.1"
consistenttime = "^0.2"
clear_on_drop ="^0.1.0"  # way better than zerodrop = "^0.1.3"
curve25519-dalek = "^0.2.0"
keystream = "^1.0.0"
chacha = "^0.1.0"
rust-crypto = "^0.2"  # replace with poly1305 and SHA3 crates

# mmap = "*"

[dev-dependencies]

