[package]
name = "Xolotl"
version = "0.0.1"
authors = ["Jeff Burdges <burdges@gnunet.org>"]

[dependencies]
rand = "^0.3"
rust-crypto = "^0.2"
consistenttime = "^0.2"
siphasher = "^0.1"
mmap = "*"
arrayref = "^0.3"
rustc-serialize = "0.3"

[dev-dependencies]

