[package]
name = "xolotl"
version = "0.0.1"
authors = ["Jeff Burdges <burdges@gnunet.org>"]

[dependencies]
rand = "^0.3"
rust-crypto = "^0.2"
consistenttime = "^0.2"
siphasher = "^0.1"
arrayref = "^0.3"
rustc-serialize = "0.3"
clear_on_drop ="^0.1.0"
# zerodrop = "^0.1.3"
# mmap = "*"

[dev-dependencies]

